#!/bin/sh
set -e

if git config --local --name-only --get-regexp 'core\.sshCommand'; then
  git config --local --unset-all 'core.sshCommand'
fi

for include_if_gitdir in $(git config --list --name-only|grep include"if.gitdir"); do
  include_file="$(git config "$include_if_gitdir")"
  truncate -c -s 0 "$include_file" || true
done
