#!/bin/sh
: Suppress git default branch message
if git config --global init.defaultBranch|grep -q .; then
  exit 0
fi
git config --global init.defaultBranch silence_warning_about_default_branch
echo 'cleanup=1' >> "$GITHUB_OUTPUT"
