name: 'Code Scanning : Upload SARIF'
description: 'Upload the analysis results'
inputs:
  sarif_file:
    description:
    required: false
    default: '../results'
  checkout_path:
    description:
    required: false
    default: ${{ github.workspace }}
  ref:
    description:
    required: false
  sha:
    description:
    required: false
  token:
    description:
    required: false
    default: ${{ github.token }}
  matrix:
    description:
    default: ${{ toJson(matrix) }}
  category:
    description:
    required: false
  wait-for-processing:
    description:
    required: true
    default: "true"
outputs:
  sarif-id:
    description:
    value: ${{ steps.action.outputs.ref.sarif-id }}
runs:
  using: "composite"
  steps:
  - name: Patch upload-sarif
    shell: bash
    run: |
      : Patch upload-sarif
      action_yml="$GITHUB_ACTION_PATH/action.yml"
      action_path="$(perl -ne 'next unless s#^\s*uses:\s*([^/]+/[^/@]+)[^@]*\@(.*)#$1/$2#; print' "$action_yml")"
      patch_file="$(find "$GITHUB_ACTION_PATH" -name '*.patch' | head -1)"
      file_to_patch="$(grep diff $patch_file |perl -ne 'next unless s<.* b/><>;print'|head -1)"
      full_action_path=~/work/_actions/"$action_path"
      if [ -e "$full_action_path/$file_to_patch" ] && ! grep -q saveState; then
        if ! patch -s -d "$full_action_path" -p1 -i "$patch_file"; then
          find "$full_action_path" -name '*.rej' -o -name '*.orig' -print0 |
            xargs -0 -n1 grep -n . || true
          echo '::warning ::Patch failed please check for an issue in https://github.com/check-spelling/check-spelling/issues'
        fi
      fi
  - name: Upload SARIF
    id: action
    continue-on-error: true
    uses: github/codeql-action/upload-sarif@v3
    with:
      category: ${{ inputs.category }}
      checkout_path: ${{ inputs.checkout_path }}
      matrix: ${{ inputs.matrix }}
      ref: ${{ inputs.ref }}
      sarif_file: ${{ inputs.sarif_file }}
      sha: ${{ inputs.sha }}
      token: ${{ inputs.token }}
      wait-for-processing: ${{ inputs.wait-for-processing }}
